export default{
    MARK_NOTIFICATIONS_AS_READ_BY_ID:'MARK_NOTIFICATIONS_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS_AS_READ:'MARK_ALL_NOTIFICATIONS_AS_READ',
    START_MASK_AS_READ:'START_MASK_AS_READ',
    FINISH_MASK_AS_READ:'FINISH_MASK_AS_READ',
    RECEIVE_NOTIFICATIONS:'RECEIVE_NOTIFICATIONS',
    START_LOGIN:'START_LOGIN',
    LOGIN_SUCESS:'LOGIN_SUCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    CHANG_AVATAR:'CHANG_AVATAR'
}